### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by sfc-gh-mholboke** [tsegall/semantic-types#1]
Wondering if there is a license to use this data or any restrictions on how it may be used?

**Comment by tsegall** [comment]
Are you asking about the original files from the Open Data Portals - or my work of attempting to provide a robust corpus for Semantic Type validation?

**Comment by sfc-gh-mholboke** [comment]
Both - thank you

**Comment by tsegall** [comment]
So improved the README, added a license to the repository, and the code to make it clear that anyone can use it.  It currently covers approximately 80 Semantic Types (for English) and a similar set (though not identical) to the Sherlock set.

**Comment by sfc-gh-mholboke** [comment]
Perfect thank you. I will close this issue
